import { defineConfig, devices } from "@playwright/test";

// Living Thread commit 13 - E2E / a11y / visual QA.
//
// These specs are runnable on a browser-capable machine:
//   npm run test:e2e:install   # one-time: playwright + chromium
//   npm run dev                # in another shell, on 127.0.0.1:3000
//   npm run test:e2e
//
// They were authored in an environment WITHOUT a browser harness, so the
// screenshots under e2e/__screenshots__ and the trace files must be
// generated by that run - they are NOT committed from here.

export default defineConfig({
  testDir: "./e2e",
  timeout: 30_000,
  fullyParallel: true,
  retries: process.env.CI ? 1 : 0,
  reporter: [["list"], ["html", { open: "never", outputFolder: "e2e/report" }]],
  use: {
    baseURL: process.env.E2E_BASE_URL ?? "http://127.0.0.1:3000",
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
  },
  projects: [
    { name: "mobile-320", use: { ...devices["iPhone SE"], viewport: { width: 320, height: 640 } } },
    { name: "mobile-390", use: { ...devices["iPhone 12"], viewport: { width: 390, height: 844 } } },
    { name: "desktop", use: { ...devices["Desktop Chrome"] } },
  ],
});
