import { defineConfig, devices } from "@playwright/test";
import { existsSync } from "node:fs";

// Living Thread - E2E / a11y / visual QA.
//
//   npm run test:e2e:install    # one-time: playwright + chromium
//   npm run test:e2e:seed       # seed the deterministic E2E user + reality
//                               # paths + e2e/.auth/user.json (needs .env)
//   npm run dev                 # app on 127.0.0.1:3000 (another shell)
//   npm run test:e2e            # E2E + first screenshot baselines
//
// These specs were authored in an environment WITHOUT a browser harness,
// so the report + screenshots must be generated by that run (they are
// gitignored, not committed).

const STORAGE = "e2e/.auth/user.json";
const HAS_STORAGE = existsSync(STORAGE);

export default defineConfig({
  testDir: "./e2e",
  timeout: 45_000,
  fullyParallel: true,
  retries: process.env.CI ? 1 : 0,
  reporter: [["list"], ["html", { open: "never", outputFolder: "e2e/report" }]],
  use: {
    baseURL: process.env.E2E_BASE_URL ?? "http://127.0.0.1:3000",
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
    // Every project runs as the seeded E2E user. Run `npm run test:e2e:seed`
    // first; without it the auth-dependent specs skip themselves.
    storageState: HAS_STORAGE ? STORAGE : undefined,
  },
  projects: [
    { name: "mobile-320", use: { ...devices["iPhone SE"], viewport: { width: 320, height: 640 } } },
    { name: "mobile-390", use: { ...devices["iPhone 12"], viewport: { width: 390, height: 844 } } },
    { name: "desktop", use: { ...devices["Desktop Chrome"] } },
  ],
});
