// Static, code-owned fund/stock catalog for the Investment Planner. This is
// deliberately NOT AI-generated and never will be: naming a real security
// with an AI-invented return figure in a banking app is a materially higher
// compliance/mis-selling risk than anything else in this codebase (compare
// to lib/retirement-finance.js's abstract "vehicle" categories, which have
// no real-world product identity to get wrong). The AI layer for this
// domain (lib/investment-prompts.js / lib/investment-tools.js) only ever
// narrates entries the code has already selected and already priced.
//
// expectedAnnualReturnPercent/expenseRatioPercent/dividendYieldPercent below
// are illustrative long-run approximations for a Singapore-banking-app
// prototype — re-verify against real factsheets before relying on this in a
// non-prototype context, same disclaimer as every other *-finance.js module
// in this codebase (see lib/loan-finance.js:8-11).

export const RISK_BANDS = ["conservative", "balanced", "growth"];
export const HOLDINGS_CATEGORIES = ["sg_equities", "global_equities", "bonds", "reits", "cash_like"];
export const PURCHASE_MODES = ["monthly_rsp", "lump_sum", "daily_micro_dca", "value_averaging"];

// Real SGX board-lot stocks/ETFs trade in 100-share lots and can't be bought
// "one share a day" without a fractional-share broker; SG unit trusts and
// most SGX names realistically support monthly RSP (OCBC BCIP-style) + lump
// sum + value-averaging top-ups. Only entries flagged
// fractionalBrokerRequired: true additionally support daily_micro_dca, so
// the mode is demonstrated on fractional-friendly global names without
// pretending every instrument works that way.
export const INVESTMENT_CATALOG = [
  // ---- Singapore market — conservative ----
  {
    id: "sg_bond_fund",
    instrumentType: "fund",
    market: "sg",
    name: "SG-domiciled Short Duration SGD Bond Fund",
    ticker: null,
    category: "bonds",
    riskBand: "conservative",
    expectedAnnualReturnPercent: 3.2,
    expenseRatioPercent: 0.45,
    dividendYieldPercent: null,
    lotSize: 1,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 1000, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 2,
    descriptionKey: "investmentPlanner.catalog.sgBondFund",
    disclosureKey: "investmentPlanner.disclosures.bondFundGeneric",
  },
  {
    id: "sg_govt_bond_etf",
    instrumentType: "fund",
    market: "sg",
    name: "ABF Singapore Bond Index Fund",
    ticker: "A35.SI",
    category: "bonds",
    riskBand: "conservative",
    expectedAnnualReturnPercent: 3.0,
    expenseRatioPercent: 0.25,
    dividendYieldPercent: 2.6,
    lotSize: 100,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 1200, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 2,
    descriptionKey: "investmentPlanner.catalog.sgGovtBondEtf",
    disclosureKey: "investmentPlanner.disclosures.bondFundGeneric",
  },
  {
    id: "sg_moneymarket_fund",
    instrumentType: "fund",
    market: "sg",
    name: "SG-domiciled SGD Money Market Fund",
    ticker: null,
    category: "cash_like",
    riskBand: "conservative",
    expectedAnnualReturnPercent: 3.0,
    expenseRatioPercent: 0.2,
    dividendYieldPercent: null,
    lotSize: 1,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 500, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 1,
    descriptionKey: "investmentPlanner.catalog.sgMoneymarketFund",
    disclosureKey: "investmentPlanner.disclosures.moneyMarketGeneric",
  },
  {
    id: "sg_reit_income_fund",
    instrumentType: "fund",
    market: "sg",
    name: "Lion-Phillip S-REIT ETF",
    ticker: "CLR.SI",
    category: "reits",
    riskBand: "conservative",
    expectedAnnualReturnPercent: 4.5,
    expenseRatioPercent: 0.5,
    dividendYieldPercent: 5.0,
    lotSize: 100,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 800, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 3,
    descriptionKey: "investmentPlanner.catalog.sgReitIncomeFund",
    disclosureKey: "investmentPlanner.disclosures.reitGeneric",
  },
  {
    id: "sg_telco_stock",
    instrumentType: "stock",
    market: "sg",
    name: "Singtel",
    ticker: "Z74.SI",
    category: "sg_equities",
    riskBand: "conservative",
    expectedAnnualReturnPercent: 4.8,
    expenseRatioPercent: null,
    dividendYieldPercent: 4.5,
    lotSize: 100,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 300, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 3,
    descriptionKey: "investmentPlanner.catalog.sgTelcoStock",
    disclosureKey: "investmentPlanner.disclosures.stockGeneric",
  },

  // ---- Singapore market — balanced ----
  {
    id: "sg_sti_etf",
    instrumentType: "fund",
    market: "sg",
    name: "SPDR Straits Times Index ETF",
    ticker: "ES3.SI",
    category: "sg_equities",
    riskBand: "balanced",
    expectedAnnualReturnPercent: 5.5,
    expenseRatioPercent: 0.3,
    dividendYieldPercent: 3.2,
    lotSize: 100,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 500, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 3,
    descriptionKey: "investmentPlanner.catalog.sgStiEtf",
    disclosureKey: "investmentPlanner.disclosures.etfGeneric",
  },
  {
    id: "sg_reit_stock",
    instrumentType: "stock",
    market: "sg",
    name: "CapitaLand Integrated Commercial Trust",
    ticker: "C38U.SI",
    category: "reits",
    riskBand: "balanced",
    expectedAnnualReturnPercent: 5.8,
    expenseRatioPercent: null,
    dividendYieldPercent: 5.2,
    lotSize: 100,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 400, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 3,
    descriptionKey: "investmentPlanner.catalog.sgReitStock",
    disclosureKey: "investmentPlanner.disclosures.stockGeneric",
  },
  {
    id: "sg_uob_stock",
    instrumentType: "stock",
    market: "sg",
    name: "United Overseas Bank",
    ticker: "U11.SI",
    category: "sg_equities",
    riskBand: "balanced",
    expectedAnnualReturnPercent: 6.2,
    expenseRatioPercent: null,
    dividendYieldPercent: 4.8,
    lotSize: 100,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 3500, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 4,
    descriptionKey: "investmentPlanner.catalog.sgUobStock",
    disclosureKey: "investmentPlanner.disclosures.stockGeneric",
  },
  {
    id: "sg_diversified_balanced_fund",
    instrumentType: "fund",
    market: "sg",
    name: "SG-domiciled Balanced Growth Unit Trust",
    ticker: null,
    category: "sg_equities",
    riskBand: "balanced",
    expectedAnnualReturnPercent: 5.8,
    expenseRatioPercent: 0.6,
    dividendYieldPercent: null,
    lotSize: 1,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 1000, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 4,
    descriptionKey: "investmentPlanner.catalog.sgDiversifiedBalancedFund",
    disclosureKey: "investmentPlanner.disclosures.etfGeneric",
  },

  // ---- Singapore market — growth ----
  {
    id: "sg_dbs_stock",
    instrumentType: "stock",
    market: "sg",
    name: "DBS Group Holdings",
    ticker: "D05.SI",
    category: "sg_equities",
    riskBand: "growth",
    expectedAnnualReturnPercent: 7.0,
    expenseRatioPercent: null,
    dividendYieldPercent: 5.5,
    lotSize: 100,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 4000, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 5,
    descriptionKey: "investmentPlanner.catalog.sgDbsStock",
    disclosureKey: "investmentPlanner.disclosures.stockGeneric",
  },
  {
    id: "sg_ocbc_stock",
    instrumentType: "stock",
    market: "sg",
    name: "OCBC Bank",
    ticker: "O39.SI",
    category: "sg_equities",
    riskBand: "growth",
    expectedAnnualReturnPercent: 6.8,
    expenseRatioPercent: null,
    dividendYieldPercent: 5.0,
    lotSize: 100,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 1700, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 5,
    descriptionKey: "investmentPlanner.catalog.sgOcbcStock",
    disclosureKey: "investmentPlanner.disclosures.stockGeneric",
  },
  {
    id: "sg_smallcap_growth_fund",
    instrumentType: "fund",
    market: "sg",
    name: "SG-domiciled Small/Mid-Cap Growth Unit Trust",
    ticker: null,
    category: "sg_equities",
    riskBand: "growth",
    expectedAnnualReturnPercent: 7.5,
    expenseRatioPercent: 0.7,
    dividendYieldPercent: null,
    lotSize: 1,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 1000, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 6,
    descriptionKey: "investmentPlanner.catalog.sgSmallcapGrowthFund",
    disclosureKey: "investmentPlanner.disclosures.etfGeneric",
  },
  {
    id: "sg_tech_growth_stock",
    instrumentType: "stock",
    market: "sg",
    name: "Venture Corporation",
    ticker: "V03.SI",
    category: "sg_equities",
    riskBand: "growth",
    expectedAnnualReturnPercent: 8.0,
    expenseRatioPercent: null,
    dividendYieldPercent: 1.0,
    lotSize: 100,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 1300, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 6,
    descriptionKey: "investmentPlanner.catalog.sgTechGrowthStock",
    disclosureKey: "investmentPlanner.disclosures.stockGeneric",
  },

  // ---- Global market — conservative ----
  {
    id: "global_bond_etf",
    instrumentType: "fund",
    market: "global",
    name: "iShares Core Global Aggregate Bond ETF",
    ticker: "CGAB.SI",
    category: "bonds",
    riskBand: "conservative",
    expectedAnnualReturnPercent: 3.8,
    expenseRatioPercent: 0.1,
    dividendYieldPercent: 2.4,
    lotSize: 100,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 500, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 3,
    descriptionKey: "investmentPlanner.catalog.globalBondEtf",
    disclosureKey: "investmentPlanner.disclosures.bondFundGeneric",
  },
  {
    id: "global_moneymarket_usd_fund",
    instrumentType: "fund",
    market: "global",
    name: "USD Money Market Fund",
    ticker: null,
    category: "cash_like",
    riskBand: "conservative",
    expectedAnnualReturnPercent: 4.5,
    expenseRatioPercent: 0.2,
    dividendYieldPercent: null,
    lotSize: 1,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 500, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 1,
    descriptionKey: "investmentPlanner.catalog.globalMoneymarketUsdFund",
    disclosureKey: "investmentPlanner.disclosures.moneyMarketGeneric",
  },
  {
    id: "global_dividend_aristocrats_etf",
    instrumentType: "fund",
    market: "global",
    name: "Global Dividend Aristocrats ETF",
    ticker: "NOBL",
    category: "global_equities",
    riskBand: "conservative",
    expectedAnnualReturnPercent: 6.0,
    expenseRatioPercent: 0.35,
    dividendYieldPercent: 2.8,
    lotSize: 1,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 500, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 4,
    descriptionKey: "investmentPlanner.catalog.globalDividendAristocratsEtf",
    disclosureKey: "investmentPlanner.disclosures.etfGeneric",
  },
  {
    id: "global_healthcare_defensive_stock",
    instrumentType: "stock",
    market: "global",
    name: "Johnson & Johnson",
    ticker: "JNJ",
    category: "global_equities",
    riskBand: "conservative",
    expectedAnnualReturnPercent: 5.5,
    expenseRatioPercent: null,
    dividendYieldPercent: 3.0,
    lotSize: 1,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 300, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 4,
    descriptionKey: "investmentPlanner.catalog.globalHealthcareDefensiveStock",
    disclosureKey: "investmentPlanner.disclosures.stockGeneric",
  },

  // ---- Global market — balanced ----
  {
    id: "global_sp500_etf",
    instrumentType: "fund",
    market: "global",
    name: "Lion-OCBC Securities S&P 500 ETF",
    ticker: "CLR.SI",
    category: "global_equities",
    riskBand: "balanced",
    expectedAnnualReturnPercent: 7.5,
    expenseRatioPercent: 0.3,
    dividendYieldPercent: 1.3,
    lotSize: 100,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 500, daily_micro_dca: 5, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "daily_micro_dca", "value_averaging"],
    fractionalBrokerRequired: true,
    suggestedMinHorizonYears: 5,
    descriptionKey: "investmentPlanner.catalog.globalSp500Etf",
    disclosureKey: "investmentPlanner.disclosures.etfGeneric",
  },
  {
    id: "global_msci_world_etf",
    instrumentType: "fund",
    market: "global",
    name: "iShares MSCI World ETF",
    ticker: "URTH",
    category: "global_equities",
    riskBand: "balanced",
    expectedAnnualReturnPercent: 7.0,
    expenseRatioPercent: 0.4,
    dividendYieldPercent: 1.8,
    lotSize: 1,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 500, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 5,
    descriptionKey: "investmentPlanner.catalog.globalMsciWorldEtf",
    disclosureKey: "investmentPlanner.disclosures.etfGeneric",
  },
  {
    id: "global_reit_etf",
    instrumentType: "fund",
    market: "global",
    name: "Global REIT ETF",
    ticker: "RWO",
    category: "reits",
    riskBand: "balanced",
    expectedAnnualReturnPercent: 5.0,
    expenseRatioPercent: 0.4,
    dividendYieldPercent: 3.8,
    lotSize: 1,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 500, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 4,
    descriptionKey: "investmentPlanner.catalog.globalReitEtf",
    disclosureKey: "investmentPlanner.disclosures.reitGeneric",
  },
  {
    id: "global_msft_stock",
    instrumentType: "stock",
    market: "global",
    name: "Microsoft",
    ticker: "MSFT",
    category: "global_equities",
    riskBand: "balanced",
    expectedAnnualReturnPercent: 8.0,
    expenseRatioPercent: null,
    dividendYieldPercent: 0.8,
    lotSize: 1,
    minInitialInvestmentByMode: { monthly_rsp: 50, lump_sum: 300, daily_micro_dca: 5, value_averaging: 50 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "daily_micro_dca", "value_averaging"],
    fractionalBrokerRequired: true,
    suggestedMinHorizonYears: 5,
    descriptionKey: "investmentPlanner.catalog.globalMsftStock",
    disclosureKey: "investmentPlanner.disclosures.stockGeneric",
  },
  {
    id: "global_balanced_allocation_fund",
    instrumentType: "fund",
    market: "global",
    name: "Global 60/40 Balanced Allocation Fund",
    ticker: null,
    category: "global_equities",
    riskBand: "balanced",
    expectedAnnualReturnPercent: 6.0,
    expenseRatioPercent: 0.5,
    dividendYieldPercent: null,
    lotSize: 1,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 500, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 4,
    descriptionKey: "investmentPlanner.catalog.globalBalancedAllocationFund",
    disclosureKey: "investmentPlanner.disclosures.etfGeneric",
  },

  // ---- Global market — growth ----
  {
    id: "global_apple_stock",
    instrumentType: "stock",
    market: "global",
    name: "Apple Inc.",
    ticker: "AAPL",
    category: "global_equities",
    riskBand: "growth",
    expectedAnnualReturnPercent: 9.0,
    expenseRatioPercent: null,
    dividendYieldPercent: 0.5,
    lotSize: 1,
    minInitialInvestmentByMode: { monthly_rsp: 50, lump_sum: 200, daily_micro_dca: 5, value_averaging: 50 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "daily_micro_dca", "value_averaging"],
    fractionalBrokerRequired: true,
    suggestedMinHorizonYears: 5,
    descriptionKey: "investmentPlanner.catalog.globalAppleStock",
    disclosureKey: "investmentPlanner.disclosures.stockGeneric",
  },
  {
    id: "global_amazon_stock",
    instrumentType: "stock",
    market: "global",
    name: "Amazon.com",
    ticker: "AMZN",
    category: "global_equities",
    riskBand: "growth",
    expectedAnnualReturnPercent: 10.0,
    expenseRatioPercent: null,
    dividendYieldPercent: null,
    lotSize: 1,
    minInitialInvestmentByMode: { monthly_rsp: 50, lump_sum: 200, daily_micro_dca: 5, value_averaging: 50 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "daily_micro_dca", "value_averaging"],
    fractionalBrokerRequired: true,
    suggestedMinHorizonYears: 6,
    descriptionKey: "investmentPlanner.catalog.globalAmazonStock",
    disclosureKey: "investmentPlanner.disclosures.stockGeneric",
  },
  {
    id: "global_nasdaq100_etf",
    instrumentType: "fund",
    market: "global",
    name: "Nasdaq-100 ETF",
    ticker: "QQQ",
    category: "global_equities",
    riskBand: "growth",
    expectedAnnualReturnPercent: 9.5,
    expenseRatioPercent: 0.2,
    dividendYieldPercent: 0.6,
    lotSize: 1,
    minInitialInvestmentByMode: { monthly_rsp: 50, lump_sum: 300, daily_micro_dca: 5, value_averaging: 50 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "daily_micro_dca", "value_averaging"],
    fractionalBrokerRequired: true,
    suggestedMinHorizonYears: 6,
    descriptionKey: "investmentPlanner.catalog.globalNasdaq100Etf",
    disclosureKey: "investmentPlanner.disclosures.etfGeneric",
  },
  {
    id: "global_emerging_markets_fund",
    instrumentType: "fund",
    market: "global",
    name: "Global Emerging Markets Equity Fund",
    ticker: null,
    category: "global_equities",
    riskBand: "growth",
    expectedAnnualReturnPercent: 8.5,
    expenseRatioPercent: 0.6,
    dividendYieldPercent: 2.0,
    lotSize: 1,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 500, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 6,
    descriptionKey: "investmentPlanner.catalog.globalEmergingMarketsFund",
    disclosureKey: "investmentPlanner.disclosures.etfGeneric",
  },
  {
    id: "global_ev_thematic_fund",
    instrumentType: "fund",
    market: "global",
    name: "Global Clean Energy & EV Thematic Fund",
    ticker: null,
    category: "global_equities",
    riskBand: "growth",
    expectedAnnualReturnPercent: 9.0,
    expenseRatioPercent: 0.75,
    dividendYieldPercent: null,
    lotSize: 1,
    minInitialInvestmentByMode: { monthly_rsp: 100, lump_sum: 500, daily_micro_dca: null, value_averaging: 100 },
    supportedPurchaseModes: ["monthly_rsp", "lump_sum", "value_averaging"],
    fractionalBrokerRequired: false,
    suggestedMinHorizonYears: 7,
    descriptionKey: "investmentPlanner.catalog.globalEvThematicFund",
    disclosureKey: "investmentPlanner.disclosures.thematicFundGeneric",
  },
];
