// Deterministic Singapore wedding cost calculators for the three highest-
// materiality, best-sourced categories: banquet/venue, photography, and
// attire. Mirrors lib/home-finance.js's discipline — the AI chooses a
// categorical tier/type (which the customer's description implies), but the
// actual dollar figure is a hardcoded rate table from real Singapore wedding
// market research, never invented by the model. Every other line item (car,
// makeup, entertainment, favors, solemnization, decor, stationery, misc
// activities) remains an AI-estimated, web-search-grounded line item as
// before — those categories have weaker sourced tier data and/or lower
// materiality, so full determinism there isn't warranted yet.
//
// Rates verified via Singapore wedding-vendor market research as of 2026-07
// (Vows.sg banquet price list, wedding photography guides, bridal gown
// rental directories). Re-verify before relying on this in a non-prototype
// context — vendor pricing drifts continuously, unlike the regulatory rates
// in home-finance.js.

// Table-based pricing is the dominant Singapore convention (1 table = 10 pax)
// for hotel/restaurant banquets, NOT linear per-head. Couples book
// ceil(guestCount/10) tables; a partial table still costs a full table.
export const BANQUET_PER_TABLE_RATES = {
  budget: 900, // community hall / simple restaurant, nett pricing (e.g. Spring Court ~S$888/table)
  mid_range: 1500, // 3-4 star hotel / established restaurant (e.g. Grand Hyatt ~S$1,588/table)
  premium: 2200, // 5-star hotel ballroom (e.g. Shangri-La/Fullerton ~S$1,888-2,188/table)
  luxury: 3200, // top-tier/iconic venues (e.g. Capella ~S$4,292/table, using a more conservative median)
};

// "++": 10% service charge + 9% GST ≈ +19.9% combined. Hotels almost always
// quote ++; standalone restaurants more often quote nett (no surcharge).
export const HOTEL_SERVICE_CHARGE_GST_MULTIPLIER = 1.199;

// Void-deck/community weddings are the one Singapore segment that genuinely
// prices per-pax rather than per-table (caterer-priced, not restaurant/hotel
// package-priced). Sourced range S$15-30/pax all-in; using the midpoint.
export const COMMUNITY_PER_PAX_RATE = 20;

export function calculateBanquetCost({ guestCount, venueTier, venueType }) {
  if (venueType === "community") {
    return {
      subtotal: Math.round(guestCount * COMMUNITY_PER_PAX_RATE),
      unit: "per guest",
      quantity: guestCount,
      unitRate: COMMUNITY_PER_PAX_RATE,
      tablesNeeded: null,
    };
  }
  const tablesNeeded = Math.max(1, Math.ceil(guestCount / 10));
  const rate = BANQUET_PER_TABLE_RATES[venueTier] ?? BANQUET_PER_TABLE_RATES.mid_range;
  const base = tablesNeeded * rate;
  const subtotal = Math.round(venueType === "hotel" ? base * HOTEL_SERVICE_CHARGE_GST_MULTIPLIER : base);
  return { subtotal, unit: "per table", quantity: tablesNeeded, unitRate: rate, tablesNeeded };
}

// Flat fees — full-coverage packages don't scale with guest count.
export const PHOTOGRAPHY_PACKAGE_RATES = {
  basic: 1350, // ROM/banquet-only, same-day-edit, 1 shooter
  mid_range: 3750, // actual-day + pre-wedding shoot, photo+video
  premium: 7500, // full-day, 2 shooters + videographer, album, drone
};

export function calculatePhotographyCost(tier) {
  return PHOTOGRAPHY_PACKAGE_RATES[tier] ?? PHOTOGRAPHY_PACKAGE_RATES.mid_range;
}

// Combined bridal gown + groom suit rental package, flat fee.
export const ATTIRE_PACKAGE_RATES = {
  budget: 750, // gown ~S$600 + suit ~S$150
  mid_range: 1450, // gown ~S$1,200 + suit ~S$250
  premium: 3000, // gown ~S$2,500+ + suit ~S$500 (suit figure extrapolated, lower confidence)
};

export function calculateAttireCost(tier) {
  return ATTIRE_PACKAGE_RATES[tier] ?? ATTIRE_PACKAGE_RATES.mid_range;
}

function tierLabel(tier) {
  return { budget: "Budget", mid_range: "Mid-range", premium: "Premium", luxury: "Luxury" }[tier] ?? tier;
}

export const DETERMINISTIC_LINE_ITEM_CATEGORIES = ["venue", "photography", "attire"];

// Composition root — always exactly 3 line items, shaped identically to the
// AI-estimated ones (category/label/unit_rate/unit/quantity/subtotal/
// estimate_basis) so they slot into the same line_items array, but with
// estimate_basis text generated by code, never invented by the model.
export function computeCoreWeddingLineItems({ guestCount, venueTier, venueType, photographyTier, attireTier }) {
  const banquet = calculateBanquetCost({ guestCount, venueTier, venueType });
  const photographySubtotal = calculatePhotographyCost(photographyTier);
  const attireSubtotal = calculateAttireCost(attireTier);

  const venueBasis =
    venueType === "community"
      ? `Void-deck/community weddings in Singapore typically run about SGD ${COMMUNITY_PER_PAX_RATE}/guest all-in, priced per head rather than per table.`
      : `${tierLabel(venueTier)} Singapore banquet venues run about SGD ${banquet.unitRate}/table of 10${
          venueType === "hotel" ? ", plus the standard 10% service charge + 9% GST (\"++\")" : ", nett"
        }.`;

  return [
    {
      category: "venue",
      label:
        venueType === "community"
          ? "Banquet (Community/Void Deck)"
          : `Banquet (${tierLabel(venueTier)}, ${banquet.tablesNeeded} tables)`,
      unit_rate: banquet.unitRate,
      unit: banquet.unit,
      quantity: banquet.quantity,
      subtotal: banquet.subtotal,
      estimate_basis: venueBasis,
    },
    {
      category: "photography",
      label: `Photography & Videography (${tierLabel(photographyTier)})`,
      unit_rate: photographySubtotal,
      unit: "flat fee",
      quantity: 1,
      subtotal: photographySubtotal,
      estimate_basis: `${tierLabel(photographyTier)} full-coverage photography/videography packages in Singapore typically run around SGD ${photographySubtotal}.`,
    },
    {
      category: "attire",
      label: `Bridal & Groom Attire (${tierLabel(attireTier)})`,
      unit_rate: attireSubtotal,
      unit: "flat fee",
      quantity: 1,
      subtotal: attireSubtotal,
      estimate_basis: `${tierLabel(attireTier)} gown + suit rental packages in Singapore typically run around SGD ${attireSubtotal}.`,
    },
  ];
}

// Frontend integration point for the guest-count slider: replaces ONLY the
// venue line item via the real table-based formula. Every other line item
// (AI-estimated long-tail categories) is left untouched here — the caller
// is responsible for applying any other guest-scaling heuristic to those.
export function recomputeVenueForGuestCount(lineItems, { venueTier, venueType }, newGuestCount) {
  return lineItems.map((item) => {
    if (item.category !== "venue") return item;
    const banquet = calculateBanquetCost({ guestCount: newGuestCount, venueTier, venueType });
    return { ...item, unit_rate: banquet.unitRate, unit: banquet.unit, quantity: banquet.quantity, subtotal: banquet.subtotal };
  });
}
